In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.1.0'

In [3]:
a=tf.constant(2,dtype=np.int8)
b=tf.constant(5,dtype=np.int8)

In [4]:
a

<tf.Tensor: shape=(), dtype=int8, numpy=2>

In [5]:
a=np.array(a)

In [6]:
a.dtype

dtype('int8')

In [7]:
a=np.array([1,2,3])
b=np.array([1,2,3])

In [8]:
a=tf.constant(a)

In [9]:
a  

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [10]:
tf.multiply(a,b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9])>

In [11]:
t=tf.constant([[1,2],[4,5]])
f=tf.constant([[1,2],[4,5]])

In [12]:
t=tf.constant(np.arange(25).reshape(5,5))

In [12]:
t*f

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [16, 25]])>

In [13]:
q=tf.matmul(t,f)

In [14]:
q

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9, 12],
       [24, 33]])>

In [15]:
a=tf.Variable(2,dtype=np.int8)

In [16]:
a

<tf.Variable 'Variable:0' shape=() dtype=int8, numpy=2>

In [17]:
a.assign(9000000)

<tf.Variable 'UnreadVariable' shape=() dtype=int8, numpy=64>

In [18]:
a.assign(128)

<tf.Variable 'UnreadVariable' shape=() dtype=int8, numpy=-128>

In [19]:
t=tf.Variable(np.random.randn(3,1))

In [20]:
t

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float64, numpy=
array([[ 0.32170709],
       [-0.36596   ],
       [ 0.11170715]])>

In [21]:
t=tf.Variable(9)

In [22]:
q=t

In [23]:
q is t

True

In [24]:
t.assign(6)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=6>

In [25]:
q is t

True

In [26]:
q

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=6>

In [27]:
a=tf.Variable(9)

In [28]:
print(a.assign_sub(11).numpy())

-2


In [29]:
a.numpy

<bound method BaseResourceVariable.numpy of <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=-2>>

In [30]:
a=tf.Variable([[1,2,3],[1,2,3]],dtype=tf.int8,name="hell")

In [31]:
a

<tf.Variable 'hell:0' shape=(2, 3) dtype=int8, numpy=
array([[1, 2, 3],
       [1, 2, 3]], dtype=int8)>

In [32]:
mat=tf.constant(np.random.randint(0,100,(5,5)))

In [33]:
tf.reduce_sum(mat,axis=0)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([179, 206, 350, 197, 249])>

In [34]:
mat

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[53, 27, 95, 47, 46],
       [17, 50, 12, 99, 25],
       [25, 15, 79,  9, 74],
       [47, 95, 92,  9, 88],
       [37, 19, 72, 33, 16]])>

In [35]:
a=tf.Variable(5)
b=tf.Variable(7)

In [36]:
tf.add(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [37]:
a+b

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [38]:
u=a+b
v=u+a
c=u+v
d=c+a+b

In [39]:
d

<tf.Tensor: shape=(), dtype=int32, numpy=41>

In [40]:
@tf.function
def toss(a,b):
    x=tf.multiply(a,b,name='boss')
    w=tf.constant(5,name='toss')            ##### always use con in function
    v=tf.constant(6)
    t=tf.add(x,w,name='t')
    p=tf.add(x,v,name='p')
    return(t+p)

In [41]:
a=tf.Variable(9)
b=tf.Variable(8)
toss(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=155>

In [42]:
@tf.function
def scopee(a,b):
    with tf.name_scope("naman"):
        z=tf.multiply(a,b)
        print(z.name)
    with tf.name_scope("aman"):
        c=tf.constant(9)
        d=tf.constant(7)
        print(c.name)
        e=tf.add(a,b)
        f=tf.add(c,d)
    return(e+f)

In [43]:
a=tf.constant(5)
b=tf.constant(6)
scopee(a,b)

naman/Mul:0
aman/Const:0


<tf.Tensor: shape=(), dtype=int32, numpy=27>

In [44]:
def sigmoid(x):
    return 1/(1 + tf.exp(-x))

In [45]:
x=tf.Variable(9.1)            ### we always neend point in sigmoid values

with tf.GradientTape() as tape:
    gr=sigmoid(x)
    
res=tape.gradient(gr,x).numpy()     
print("the value of sigmoid fun on 0 is",res)

the value of sigmoid fun on 0 is 0.00011164082


In [46]:
def op(w):
    k=tf.constant(5,dtype=tf.float32)
    s=(w*w)+k
    sq=s*s
    return sq
    
for i in range(10):
    with tf.GradientTape() as tape:
        w=tf.Variable(i,dtype=tf.float32)
        ret=op(w)
        res=tape.gradient(ret,w)
        print(res.numpy())

0.0
24.0
72.0
168.0
336.0
600.0
984.0
1512.0
2208.0
3096.0
