In [1]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense,SimpleRNN,Embedding,Input
from tensorflow.keras.preprocessing import sequence
import numpy as np
import pandas as pd

from tensorflow.keras.datasets import imdb

In [11]:
(x_train, y_train), (x_test, y_test)=imdb.load_data(num_words=10000,maxlen=200,index_from=0)

In [25]:
len(x_train[1])
#x_train.shape

141

In [13]:
vocab=imdb.get_word_index()

In [14]:
vocab_values=dict(zip(vocab.values(),vocab.keys()))

In [28]:
len(vocab_values)

88584

In [15]:
vocab_values[1]

'the'

In [7]:
#x_train[0]

In [8]:
#[vocab_values[index-3] for index  in x_train[0] if index >=3]   #### sir code 

## otherwise change the value of index_form when loading  data from imdb

" ".join([vocab_values[index] for index in x_train[0]])

"the big hair big boobs bad music and a giant safety pin these are the words to best describe this terrible movie i love cheesy horror movies and i've seen hundreds but this had got to be on of the worst ever made the plot is paper thin and ridiculous the acting is an abomination the script is completely laughable the best is the end showdown with the cop and how he worked out who the killer is it's just so damn terribly written the clothes are sickening and funny in equal and the hair is big lots of boobs and men wear those cut and shirts that show off their and sickening that men actually wore them and the music is just and trash that plays over and over again in almost every scene there is trashy music boobs and and taking away bodies and the gym still doesn't close for and all joking aside this is a truly bad film whose only charm is to look back on the disaster that was the 80's and have a good old laugh at how bad everything was back then"

In [9]:
x_train_padded=sequence.pad_sequences(x_train,maxlen=200)
x_test_padded=sequence.pad_sequences(x_test,maxlen=200)

In [10]:
#x_train_padded[0]
len(x_test_padded[0])

200

In [32]:
in_layer=Input(shape=(200,))
embad=Embedding(input_dim=10000 , output_dim=100)(in_layer)
rnn=SimpleRNN(units=40)(embad)
out=Dense(units=1,activation="sigmoid")(rnn)

In [25]:
model=Model(inputs=in_layer,outputs=out)

In [26]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 200)]             0         
_________________________________________________________________
embedding_3 (Embedding)      (None, 200, 100)          1000000   
_________________________________________________________________
simple_rnn_3 (SimpleRNN)     (None, 40)                5640      
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 41        
Total params: 1,005,681
Trainable params: 1,005,681
Non-trainable params: 0
_________________________________________________________________


In [27]:
model.compile(optimizer='rmsprop',loss="binary_crossentropy",metrics=["accuracy"])

## We are not using adam because adam consist of gradient decent and rmsprop soo in our case gradient_decent 
##  will fail beacause of local minima prop

In [28]:
model.fit(x_train_padded,y_train,epochs=10,batch_size=1000,steps_per_epoch=10)

Train on 25000 samples
Epoch 1/10
10000/25000 [===========>..................] - ETA: 5s - loss: 0.3048 - accuracy: 0.8808

In [33]:
model.evaluate(x_test_padded,y_test,verbose=0)

[0.4669915369152261, 0.7817531]

In [34]:
model.predict(x_test_padded[:10])

array([[0.83432555],
       [0.21771686],
       [0.7489253 ],
       [0.10407829],
       [0.6767976 ],
       [0.31482568],
       [0.29073903],
       [0.12203062],
       [0.65085864],
       [0.21760207]], dtype=float32)

In [35]:
from sklearn.feature_extraction.text import CountVectorizer

In [36]:
from nltk.tokenize import word_tokenize

In [37]:
line="Kartik is a very good actor and he played in movies very good"

sent=word_tokenize(line)

final=[vocab[index] for index in sent if index in vocab]

final

x_final_padded=sequence.pad_sequences([final],maxlen=200)

model.predict([x_final_padded])

array([[0.893232]], dtype=float32)

In [22]:
a=model.predict(x_test_padded)

In [23]:
b=[]
for i in range(len(a)):
    if a[i]>.5:
        b.append(1)
    else:
        b.append(0)

In [24]:
len(b)

3913

In [25]:
len(x_test_padded)

3913

In [26]:
acc=np.sum(y_test==b)/len(y_test)

In [27]:
acc

0.8540761564017378

In [28]:
b[:10]

[0, 0, 1, 0, 1, 0, 0, 0, 1, 0]

In [29]:
y_test[:10]

array([0, 0, 1, 0, 1, 0, 0, 0, 1, 0], dtype=int64)