In [1]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense,Embedding,SimpleRNN,Input

In [2]:
import numpy as np

In [3]:
from tensorflow.keras.preprocessing import sequence

In [4]:
from tensorflow.keras.datasets import imdb

In [5]:
(x_train, y_train), (x_test, y_test)=imdb.load_data(num_words=10000,index_from=0,maxlen=200)

In [25]:
len(x_train)

25000

In [8]:
vocab=imdb.get_word_index()

In [17]:
vocab_values=dict(zip(vocab.values(),vocab.keys()))

In [36]:
" ".join([vocab_values[val] for val in x_train[1] if val in vocab_values])

"the this has to be one of the worst films of the 1990s when my friends i were watching this film being the target audience it was aimed at we just sat watched the first half an hour with our jaws touching the floor at how bad it really was the rest of the time everyone else in the theatre just started talking to each other leaving or generally crying into their popcorn that they actually paid money they had and working to watch this feeble excuse for a film it must have looked like a great idea on paper but on film it looks like no one in the film has a clue what is going on crap acting crap costumes i can't get across how and this is to watch save yourself an hour a bit of your life"

In [37]:
x_train_pad=sequence.pad_sequences(x_train,maxlen=200)

In [87]:
x_test_pad=sequence.pad_sequences(x_test,maxlen=200)

In [39]:
in_layer=Input(shape=(200,))
embad=Embedding(input_dim=10000,output_dim=100)(in_layer)
rnn=SimpleRNN(units=40)(embad)
out=Dense(units=1,activation="sigmoid")(rnn)

In [40]:
model=Model(inputs=in_layer,outputs=out)

In [41]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 200)]             0         
_________________________________________________________________
embedding (Embedding)        (None, 200, 100)          1000000   
_________________________________________________________________
simple_rnn (SimpleRNN)       (None, 40)                5640      
_________________________________________________________________
dense (Dense)                (None, 1)                 41        
Total params: 1,005,681
Trainable params: 1,005,681
Non-trainable params: 0
_________________________________________________________________


In [42]:
model.compile(optimizer='rmsprop',loss="binary_crossentropy",metrics=["accuracy"])

In [44]:
model.fit(x_train_pad,y_train,batch_size=1000,steps_per_epoch=20,epochs=5)

Train on 25000 samples
Epoch 1/5
20000/25000 [=======================>......] - ETA: 2s - loss: 0.2093 - accuracy: 0.9205

In [45]:
model.predict(x_test_pad[:10])

array([[0.03360806],
       [0.05455645],
       [0.07311987],
       [0.28311887],
       [0.96381485],
       [0.15127896],
       [0.05372138],
       [0.05239251],
       [0.04337428],
       [0.02055209]], dtype=float32)

In [46]:
y_test[:10]

array([0, 0, 1, 0, 1, 0, 0, 0, 1, 0], dtype=int64)

In [47]:
from nltk.tokenize import word_tokenize

In [60]:
line="This is very good movie..Kartik dont like it"

word=word_tokenize(line)

fin=[vocab[w] for w in word if w in vocab]

final=sequence.pad_sequences([fin],maxlen=200)
model.predict(final)

array([[0.8602522]], dtype=float32)

In [88]:
a=model.predict(x_test_pad)

In [89]:
b=[]
for val in range(len(a)):

    if a[[val]]>.5:
        b.append(1)
    else:
        b.append(0)

In [90]:
len(b)

3913

In [91]:
acc=np.sum(y_test==b)/len(y_test)

In [92]:
acc

0.8821875798619985