In [1]:
from sklearn.datasets import make_blobs
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import tensorflow as tf

In [3]:
import warnings

warnings.filterwarnings("ignore")

In [4]:
class Layer:
    
    def __init__(self,unit,inputs,activation):
        self.unit=unit
        self.inputs=inputs
        self.weight=tf.Variable(tf.zeros([inputs,unit],dtype=tf.float64))
        self.activation=activation
        self.bias=tf.Variable(tf.zeros((unit),dtype=tf.float64))
        
class Model:
    
    def __init__(self,inputs):
        self.input=inputs
        self.output=inputs
        self.layers=[]
    
    def add_layer(self, units, activation=tf.sigmoid):
        layer = Layer(units, self.output, activation)
        self.layers.append(layer)
        self.output = units
        
    def predict(self,X):
        a=X
        for layer in self.layers:
            a=layer.activation(tf.matmul(a , layer.weight) + layer.bias)
            layer.result=a
        return a

In [13]:
model = Model(inputs=100)
model.add_layer(50)
model.add_layer(30)
model.add_layer(10)

In [14]:
X = tf.constant(np.random.randn(100, 100))

In [15]:
out=model.predict(X)

In [16]:
model.layers[1].result

<tf.Tensor: shape=(100, 30), dtype=float64, numpy=
array([[0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5],
       ...,
       [0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5]])>

In [17]:
data=tf.constant([1.,5.,6.])

In [19]:
tf.sigmoid(data)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.7310586, 0.9933072, 0.9975274], dtype=float32)>

In [20]:
tf.math.exp(data)/tf.reduce_mean(data)*tf.math.exp(data)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.8472639e+00, 5.5066167e+03, 4.0688699e+04], dtype=float32)>