In [1]:
import numpy as np

In [3]:
a=np.array([12,23,23])

In [4]:
a.shape

(3,)

In [5]:
a.size

3

In [6]:
a.dtype

dtype('int32')

In [7]:
b=np.array([12,4,3],dtype=np.int8)

In [8]:
b.dtype

dtype('int8')

In [11]:
c=np.array([[11,12,23],[3,23,23]])

In [12]:
c.shape

(2, 3)

In [13]:
c.size

6

In [14]:
c.dtype

dtype('int32')

In [16]:
d=np.array([[12,34,234],[43,324,113]],dtype=np.int64)

In [17]:
d.dtype

dtype('int64')

In [19]:
e=np.array([[12,43],[234,23,23]])

In [20]:
e.shape

(2,)

In [21]:
e.size

2

In [24]:
f=np.array([[[12],[12],[34]],[[12],[12],[34]]])

In [25]:
f.shape

(2, 3, 1)

In [26]:
np.array(range(100))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [28]:
np.arange(100)  #### same as range property of numpy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [29]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [33]:
a=np.arange(12)

In [34]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
b=a.reshape(4,3)

In [36]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
third=a.reshape(3,1,2,1,2)

In [38]:
third

array([[[[[ 0,  1]],

         [[ 2,  3]]]],



       [[[[ 4,  5]],

         [[ 6,  7]]]],



       [[[[ 8,  9]],

         [[10, 11]]]]])

In [39]:
third.ndim

5

In [40]:
a[0]=1000

In [41]:
b

array([[1000,    1,    2],
       [   3,    4,    5],
       [   6,    7,    8],
       [   9,   10,   11]])

In [45]:
a=np.arange(15)

In [46]:
b=a.reshape(5,1,1,1,1,1,3)

In [47]:
b

array([[[[[[[ 0,  1,  2]]]]]],





       [[[[[[ 3,  4,  5]]]]]],





       [[[[[[ 6,  7,  8]]]]]],





       [[[[[[ 9, 10, 11]]]]]],





       [[[[[[12, 13, 14]]]]]]])

In [48]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [49]:
a[0]=122

In [50]:
a

array([122,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [51]:
b

array([[[[[[[122,   1,   2]]]]]],





       [[[[[[  3,   4,   5]]]]]],





       [[[[[[  6,   7,   8]]]]]],





       [[[[[[  9,  10,  11]]]]]],





       [[[[[[ 12,  13,  14]]]]]]])

In [52]:
c=b.astype(float)

In [53]:
c

array([[[[[[[122.,   1.,   2.]]]]]],





       [[[[[[  3.,   4.,   5.]]]]]],





       [[[[[[  6.,   7.,   8.]]]]]],





       [[[[[[  9.,  10.,  11.]]]]]],





       [[[[[[ 12.,  13.,  14.]]]]]]])

In [54]:
b

array([[[[[[[122,   1,   2]]]]]],





       [[[[[[  3,   4,   5]]]]]],





       [[[[[[  6,   7,   8]]]]]],





       [[[[[[  9,  10,  11]]]]]],





       [[[[[[ 12,  13,  14]]]]]]])

In [55]:
## astype change make the new array object in native

In [56]:
np,zeroes?

Object `zeroes` not found.


In [58]:
np.zeros?

Docstring:
zeros(shape, dtype=float, order='C')

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Also
--------
zeros_like : Return an array of zeros with shape and type of input.
empty : Return a new uninitialized array.
ones : Return a new array setting values to one.
full : Return a new array of given shape filled with value.

Examples
--------
>>> np.zeros(5)
array([ 0.,  0.,  0.,  0.,  0.])

>>> np.zeros((5,), dtype=int)
array([0, 0, 0, 0, 0])

>>> np.zeros((2, 1))
array([[ 0.],
      

In [59]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [61]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [62]:
np.full((5,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [63]:
np.full?

Signature: np.full(shape, fill_value, dtype=None, order='C')
Docstring:
Return a new array of given shape and type, filled with `fill_value`.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
fill_value : scalar
    Fill value.
dtype : data-type, optional
    The desired data-type for the array  The default, `None`, means
     `np.array(fill_value).dtype`.
order : {'C', 'F'}, optional
    Whether to store multidimensional data in C- or Fortran-contiguous
    (row- or column-wise) order in memory.

Returns
-------
out : ndarray
    Array of `fill_value` with the given shape, dtype, and order.

See Also
--------
full_like : Return a new array with shape of input filled with value.
empty : Return a new uninitialized array.
ones : Return a new array setting values to one.
zeros : Return a new array setting values to zero.

Examples
--------
>>> np.full((2, 2), np.inf)
array([[ inf,  inf],
       [ inf,  inf]])
>>> np.full((2, 2), 

In [66]:
np.full((5,5),10,dtype=float)

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])