In [1]:
import numpy as np

In [2]:
a=np.array([2,4,3])

In [3]:
a

array([2, 4, 3])

In [4]:
b=np.array([5,6,7])

In [5]:
b

array([5, 6, 7])

In [25]:
sum(a,b)

array([14, 15, 16])

In [38]:
np.add(a,b)

array([ 7, 10, 10])

In [39]:
np.sum(a,axis=0)

9

In [45]:
a=np.arange(25).reshape(5,5)

In [51]:
a.min()

0

In [60]:
b=np.arange(25).reshape(5,5)

In [61]:
b.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [77]:
a=np.array([[1,2],[3,4]])

In [78]:
a

array([[1, 2],
       [3, 4]])

In [79]:
b=np.array([[5,6],[7,8]])

In [80]:
a@b

array([[19, 22],
       [43, 50]])

In [82]:
a*b

array([[ 5, 12],
       [21, 32]])

In [83]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [84]:
## pandas

In [88]:
import pandas as pd
import numpy as np

In [94]:
dp=pd.DataFrame(np.random.randint(10,20,(4,4)),index=list("ABCD"),columns=list("WXYZ"))

In [95]:
dp

W   X   Y   Z
A  18  19  12  17
B  10  14  19  18
C  14  17  13  12
D  16  14  19  10

In [113]:
dp.sort_index(axis=0,ascending=False)

W   X   Y   Z
D  16  14  19  10
C  14  17  13  12
B  10  14  19  18
A  18  19  12  17

In [119]:
dp.sort_values(by='Y',axis=0)

W   X   Y   Z
A  18  19  12  17
C  14  17  13  12
B  10  14  19  18
D  16  14  19  10

In [120]:
dp[1:3]

W   X   Y   Z
B  10  14  19  18
C  14  17  13  12

In [121]:
dp

W   X   Y   Z
A  18  19  12  17
B  10  14  19  18
C  14  17  13  12
D  16  14  19  10

In [129]:
#dp=[1:3,axis=1]     ## error

In [128]:
dp['W']

A    18
B    10
C    14
D    16
Name: W, dtype: int32

In [132]:
dp.loc["A":"B","W":"Y"]

W   X   Y
A  18  19  12
B  10  14  19

In [134]:
dp["X"]>15

A     True
B    False
C     True
D    False
Name: X, dtype: bool

In [136]:
dp.loc[dp["X"]>15,dp.loc["B"]<18]

W   X
A  18  19
C  14  17

In [137]:
## linear regression