In [1]:
import numpy as np

In [4]:
a=np.arange(30).reshape(5,6)

In [5]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [9]:
a = np.array([[3,4,5],[6,7,8]])
b= np.array([[7,8,5],[8,2,5]])

In [7]:
a

array([[3, 4, 5],
       [6, 7, 8]])

In [11]:
np.add(a,b)

array([[10, 12, 10],
       [14,  9, 13]])

In [13]:
a.sum(axis=1)

array([12, 21])

In [14]:
import pandas as pd

In [24]:
a=pd.DataFrame([[1,2,3],[4,3,3],[5,5,4]],index=list("abc"),columns=list("def"))

In [25]:
a

d  e  f
a  1  2  3
b  4  3  3
c  5  5  4

In [27]:
a.describe()

d         e         f
count  3.000000  3.000000  3.000000
mean   3.333333  3.333333  3.333333
std    2.081666  1.527525  0.577350
min    1.000000  2.000000  3.000000
25%    2.500000  2.500000  3.000000
50%    4.000000  3.000000  3.000000
75%    4.500000  4.000000  3.500000
max    5.000000  5.000000  4.000000

In [67]:
a.loc[:,"d"]

a    1
b    4
c    5
Name: d, dtype: int64

In [54]:
a.loc['a':'c','d':'e']

d  e
a  1  2
b  4  3
c  5  5

In [75]:
a.iloc[2]

d    5
e    5
f    4
Name: c, dtype: int64

In [1]:

import pandas as pd
import numpy as np

In [2]:
np.append([1,2,4,4],[1,1])

array([1, 2, 4, 4, 1, 1])

In [3]:
np.concatenate([[3,2],[4,5]])

array([3, 2, 4, 5])

In [4]:
a=np.array([[1,2,4],[4,5,6]])

In [5]:
a

array([[1, 2, 4],
       [4, 5, 6]])

In [6]:
b=pd.DataFrame([[1,2,3],[4,5,6]])

In [7]:
b

0  1  2
0  1  2  3
1  4  5  6

In [10]:
np.append([1,2,4],b)

array([1, 2, 4, 1, 2, 3, 4, 5, 6], dtype=int64)

In [9]:
c.data

In [68]:
a

array([[1, 2, 4],
       [4, 5, 6]])

In [69]:
b

0  1  2
0  1  2  3
1  4  5  6

In [12]:
a.shape  ### first is row and second is col

(2, 3)

In [13]:
a.size

6

In [14]:
a.dtype

dtype('int32')

In [36]:
a=np.array([[1.2,2,4],[1,2,3]])

In [26]:
a

array([[1.2, 2. , 4. ],
       [1. , 2. , 3. ]])

In [27]:
a.itemsize

8

In [34]:
a=np.array([1,2,4],dtype=complex)

In [35]:
a

array([1.+0.j, 2.+0.j, 4.+0.j])

In [46]:
a=np.zeros([3,4,5])

In [50]:
a=np.ones([2,3])

In [51]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [55]:
a=np.empty([9,9])

In [56]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [70]:
a=np.arange(5.70,80.90,7)

In [71]:
a

array([ 5.7, 12.7, 19.7, 26.7, 33.7, 40.7, 47.7, 54.7, 61.7, 68.7, 75.7])

In [69]:
a.mean()

40.0

In [75]:
a=np.linspace(2,80,9)

In [76]:
a

array([ 2.  , 11.75, 21.5 , 31.25, 41.  , 50.75, 60.5 , 70.25, 80.  ])

In [79]:
a=np.arange(90).reshape(9,10)

In [80]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [81]:
a=np.arange(60)

In [82]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [209]:
a=np.arange(25).reshape(5,5)
b=np.arange(25).reshape(5,5)

In [137]:
a

array([0, 1, 2, 3, 4])

In [138]:
a*b

array([ 0.,  2.,  6., 12., 20.])

In [139]:
a@b

40.0

In [140]:
a.dot(b)

40.0

In [141]:
a=a+b

In [112]:
a

array([1, 3, 5, 7, 9])

In [207]:
a=np.random.random([2,10])

In [208]:
a

array([[0.50770395, 0.3409635 , 0.44877047, 0.47448398, 0.91397515,
        0.04618189, 0.92293677, 0.90172027, 0.7391595 , 0.27995155],
       [0.13054319, 0.03199888, 0.37753775, 0.2068593 , 0.83099081,
        0.12889118, 0.18499824, 0.61089814, 0.08843991, 0.34783344]])

In [211]:
sum(a,b)

array([[50, 56, 62, 68, 74],
       [55, 61, 67, 73, 79],
       [60, 66, 72, 78, 84],
       [65, 71, 77, 83, 89],
       [70, 76, 82, 88, 94]])

In [212]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [220]:
a=np.array([[1,2,3,4],[5,6,7,8]])
b=np.array([5,6,7,8])

In [224]:
np.add(a,b)

array([[ 6,  8, 10, 12],
       [10, 12, 14, 16]])

In [241]:
a=np.arange(5)**3

In [244]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [243]:
a

array([ 0,  1,  8, 27, 64], dtype=int32)

In [237]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [233]:
a

<ufunc 'exp'>

In [240]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [297]:
def f(x,y):
    return 10*x+y
a=np.fromfunction(f,(2,2),dtype=int)
b=np.fromfunction(f,(2,2),dtype=int)

In [296]:
a

array([[ 0,  1],
       [10, 11]])

In [261]:
a[1:3]

array([[10., 11., 12.],
       [20., 21., 22.]])

In [263]:
a[2,2]

22.0

In [274]:
a[...,2]   ## to selct all

array([ 2., 12., 22.])

In [277]:
for b in a.flat:
    print(b)

0.0
1.0
2.0
10.0
11.0
12.0
20.0
21.0
22.0


In [290]:
a

array([[ 0.,  1.,  2., 10., 11., 12., 20., 21., 22.]])

In [279]:
a.T

array([[ 0., 10., 20.],
       [ 1., 11., 21.],
       [ 2., 12., 22.]])

In [287]:
a.resize(1,9)

In [288]:
a

array([[ 0.,  1.,  2., 10., 11., 12., 20., 21., 22.]])

In [299]:
a

array([[ 0,  1],
       [10, 11]])

In [298]:
b

array([[ 0,  1],
       [10, 11]])

In [301]:
np.vstack((a,b))

array([[ 0,  1],
       [10, 11],
       [ 0,  1],
       [10, 11]])

In [302]:
np.hstack((a,b))

array([[ 0,  1,  0,  1],
       [10, 11, 10, 11]])

In [303]:
a

array([[ 0,  1],
       [10, 11]])

In [304]:
b

array([[ 0,  1],
       [10, 11]])

In [305]:
c=a

In [306]:
a[1,1]=10

In [307]:
c

array([[ 0,  1],
       [10, 10]])

In [313]:
c=a.copy()

In [314]:
c[0,1]=000000

In [315]:
c

array([[ 0,  0],
       [10, 10]])

In [316]:
a

array([[    0, 10000],
       [   10,    10]])