In [227]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import make_blobs

In [228]:
x,y=make_blobs(centers=2,n_features=2,random_state=42)

In [229]:
class customLogistic :
    
    def __init__(self,lr=1,maxstep=100):
        self.lr=lr
        self.maxstep=maxstep
    
    def fit(self,x,y):
        x=np.hstack([np.ones((x.shape[0],1)),x])
        self.theta = np.random.randn(x.shape[1], 1)
        #print("inital theta will be",self.theta)
        #print(""" break""")
        for i in range(self.maxstep):
            self.gradient_ascend(x,y)
    
    def gradient_ascend(self,x,y):
        delta_theta=self.ascend(x,y)
        #print(self.theta,"hello",delta_theta)
        #print(self.theta.shape)
        self.theta+=delta_theta
        
    def ascend(self,x,y):
        ya=y.reshape(-1,1)
        yp=self.hypo(x)
        diff=yp-ya
        dlltheta=np.dot(x.T,diff)/len(x)
        
        return -dlltheta*self.lr
        
    def hypo(self,x):
        g=np.dot(x,self.theta)
        return 1 / (1+np.exp(-g))
    
    def predict(self,x):
        x=np.hstack([np.ones((x.shape[0],1)),x])
        result = self.hypo(x)
        return (result > 0.5).astype(int).flatten()
    
    def score(self,x,y):
        yp=self.predict(x)
        return (yp==y).mean()

In [230]:
a=customLogistic()

In [231]:
a.fit(x,y)

In [199]:
c=a.predict(x[:10])

In [213]:
x=np.hstack([np.ones((x.shape[0],1)),x])
theta = np.random.randn(x.shape[1], 1)
g=np.dot(x,theta)

In [142]:
x,y=make_blobs(centers=2,n_features=2,random_state=42)

In [214]:
a.hypo(x[:10])

array([[6.52064863e-10],
       [9.99841552e-01],
       [3.47768753e-10],
       [9.98869668e-01],
       [9.98201888e-01],
       [3.03103610e-10],
       [9.99256362e-01],
       [9.83535227e-01],
       [6.18278371e-09],
       [3.38760534e-10]])

In [234]:
(c[:5]>.5).astype(int).flatten()

array([0, 1, 0, 1, 1])

In [215]:
c[:5]

array([[6.52064863e-10],
       [9.99841552e-01],
       [3.47768753e-10],
       [9.98869668e-01],
       [9.98201888e-01]])

In [20]:
a.predict(x[:10])

array([0, 1, 0, 1, 1, 0, 1, 1, 0, 0])

In [21]:
y[:10]

array([0, 1, 0, 1, 1, 0, 1, 1, 0, 0])

In [22]:
a.score(x,y)

1.0

In [23]:
model=LogisticRegression()

In [24]:
model.fit(x,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [25]:
model.predict(x[:10])

array([0, 1, 0, 1, 1, 0, 1, 1, 0, 0])

In [26]:
a.predict(x[:10])

array([0, 1, 0, 1, 1, 0, 1, 1, 0, 0])