In [20]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import make_blobs

In [21]:
x,y=make_blobs(centers=2,n_features=2,random_state=42)

In [22]:
class customLogistic :
    
    def __init__(self,lr=1,maxstep=10):
        self.lr=lr
        self.maxstep=maxstep
    
    def fit(self,x,y):
        x=np.hstack([np.ones((x.shape[0],1)),x])
        self.theta = np.random.randn(x.shape[1], 1)
        
        for i in range(self.maxstep):
            self.gradient_ascend(x,y)
    
    def gradient_ascend(self,x,y):
        delta_theta=self.ascend(x,y)
        self.theta+=delta_theta
        
    def ascend(self,x,y):
        ya=y.reshape(-1,1)
        yp=self.hypo(x)
        diff=yp-ya
        dlltheta=np.dot(x.T,diff)/len(x)
        
        return -dlltheta*self.lr
        
    def hypo(self,x):
        g=np.dot(x,self.theta)
        return 1 / (1+np.exp(-g))
    
    def predict(self,x):
        x=np.hstack([np.ones((x.shape[0],1)),x])
        result = self.hypo(x)
        return (result > 0.5).astype(int).flatten()
    
    def score(self,x,y):
        yp=self.predict(x)
        return (yp==y).mean()

In [23]:
a=customLogistic()

In [24]:
a.fit(x,y)

In [25]:
a.predict(x[:10])

array([0, 1, 0, 1, 1, 0, 1, 1, 0, 0])

In [26]:
y[:10]

array([0, 1, 0, 1, 1, 0, 1, 1, 0, 0])

In [27]:
a.score(x,y)

1.0

In [28]:
model=LogisticRegression()

In [29]:
model.fit(x,y)

C:\Users\Naman\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [30]:
model.predict(x[:10])

array([0, 1, 0, 1, 1, 0, 1, 1, 0, 0])

In [31]:
a.predict(x[:10])

array([0, 1, 0, 1, 1, 0, 1, 1, 0, 0])